server:
  port: 8086
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL8.x驱动类
    url: jdbc:mysql://localhost:3306/snake?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root  # 你的MySQL用户名（默认root）
    password: 123456wang566  # 你的MySQL密码
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 4
          min-idle: 1

mybatis-plus:
  mapper-locations: classpath*:/mappers/*.xml